#!/usr/bin/env python

# (C) Copyright 2009 Ioannis Aslanidis
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Library General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA 02111-1307, USA.

import Queue
import sys
import logging
import threading

import pylsyncd

from optparse import OptionParser

log = logging.getLogger("pylsyncd")
log.setLevel(logging.WARNING)

version = '%prog version 0.1'
usage = 'Usage: %prog [options] <directory to watch> <rsync destinations...>'

parser = OptionParser(usage=usage, version=version)

parser.add_option("-d", "--debug", action="store_true",
                  dest="debug", help="Debug mode")
parser.add_option("-v", "--verbose", action="store_true",
                  dest="verbose", help="Verbose mode")
parser.add_option("-q", "--quiet", action="store_true",
                  dest="quiet", help="Only print errors")

(options, args) = parser.parse_args()

if len(args) < 2:
  parser.print_help()
  sys.exit(1)

if options.verbose:
  log.setLevel(logging.INFO)
if options.quiet:
  log.setLevel(logging.ERROR)
if options.debug:
  log.setLevel(logging.DEBUG)
  pylsyncd.pyinotify.log.setLevel(logging.DEBUG)

log.info('Starting up... (%s)' % parser.get_version())
pylsyncd.init(args[0], args[1:])
pylsyncd.loop()

